name: Build

on:
  push:
  pull_request:

env:
  BUN_VERSION: '1.2.15'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build
